# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x06raftpb\"5\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"x\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x04\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\x12\x12\n\nlamport_ts\x18\x05 \x01(\x04\"J\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x12\n\nlamport_ts\x18\x03 \x01(\x04\"\xb1\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\x04\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12!\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x10.raftpb.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\x12\x12\n\nlamport_ts\x18\x07 \x01(\x04\"v\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rconflict_term\x18\x03 \x01(\x04\x12\x16\n\x0e\x63onflict_index\x18\x04 \x01(\x04\x12\x12\n\nlamport_ts\x18\x05 \x01(\x04\x32\x97\x01\n\x0bRaftService\x12\x46\n\rAppendEntries\x12\x19.raftpb.AppendEntriesArgs\x1a\x1a.raftpb.AppendEntriesReply\x12@\n\x0bRequestVote\x12\x17.raftpb.RequestVoteArgs\x1a\x18.raftpb.RequestVoteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=22
  _globals['_LOGENTRY']._serialized_end=75
  _globals['_REQUESTVOTEARGS']._serialized_start=77
  _globals['_REQUESTVOTEARGS']._serialized_end=197
  _globals['_REQUESTVOTEREPLY']._serialized_start=199
  _globals['_REQUESTVOTEREPLY']._serialized_end=273
  _globals['_APPENDENTRIESARGS']._serialized_start=276
  _globals['_APPENDENTRIESARGS']._serialized_end=453
  _globals['_APPENDENTRIESREPLY']._serialized_start=455
  _globals['_APPENDENTRIESREPLY']._serialized_end=573
  _globals['_RAFTSERVICE']._serialized_start=576
  _globals['_RAFTSERVICE']._serialized_end=727
# @@protoc_insertion_point(module_scope)
