# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tester_pb2 as tester__pb2


class TesterCommNodeServiceStub(object):
    """tester -> node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Prepare',
                request_serializer=tester__pb2.PrepareReq.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)
        self.Run = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Run',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Kill',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Disconnect',
                request_serializer=tester__pb2.ConnOpt.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)
        self.Reconnect = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Reconnect',
                request_serializer=tester__pb2.ConnOpt.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)
        self.GetRPCStats = channel.unary_unary(
                '/testerpb.TesterCommNodeService/GetRPCStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tester__pb2.RPCStats.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/testerpb.TesterCommNodeService/GetState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tester__pb2.State.FromString,
                _registered_method=True)
        self.Propose = channel.unary_unary(
                '/testerpb.TesterCommNodeService/Propose',
                request_serializer=tester__pb2.ProposalReq.SerializeToString,
                response_deserializer=tester__pb2.ProposalResult.FromString,
                _registered_method=True)
        self.ProposeSync = channel.unary_unary(
                '/testerpb.TesterCommNodeService/ProposeSync',
                request_serializer=tester__pb2.ProposalReq.SerializeToString,
                response_deserializer=tester__pb2.ProposalResult.FromString,
                _registered_method=True)
        self.Apply = channel.unary_stream(
                '/testerpb.TesterCommNodeService/Apply',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tester__pb2.ApplyResult.FromString,
                _registered_method=True)


class TesterCommNodeServiceServicer(object):
    """tester -> node
    """

    def Prepare(self, request, context):
        """Control RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """rpc ConnectPeers(google.protobuf.Empty) returns (CmdReply) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRPCStats(self, request, context):
        """Testing-related RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Apply(self, request, context):
        """streaming service for Apply
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesterCommNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=tester__pb2.PrepareReq.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=tester__pb2.ConnOpt.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
            'Reconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconnect,
                    request_deserializer=tester__pb2.ConnOpt.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
            'GetRPCStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRPCStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tester__pb2.RPCStats.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tester__pb2.State.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=tester__pb2.ProposalReq.FromString,
                    response_serializer=tester__pb2.ProposalResult.SerializeToString,
            ),
            'ProposeSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeSync,
                    request_deserializer=tester__pb2.ProposalReq.FromString,
                    response_serializer=tester__pb2.ProposalResult.SerializeToString,
            ),
            'Apply': grpc.unary_stream_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tester__pb2.ApplyResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testerpb.TesterCommNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testerpb.TesterCommNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TesterCommNodeService(object):
    """tester -> node
    """

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Prepare',
            tester__pb2.PrepareReq.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Run',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Kill',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Disconnect',
            tester__pb2.ConnOpt.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Reconnect',
            tester__pb2.ConnOpt.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRPCStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/GetRPCStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tester__pb2.RPCStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/GetState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tester__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/Propose',
            tester__pb2.ProposalReq.SerializeToString,
            tester__pb2.ProposalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommNodeService/ProposeSync',
            tester__pb2.ProposalReq.SerializeToString,
            tester__pb2.ProposalResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/testerpb.TesterCommNodeService/Apply',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tester__pb2.ApplyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TesterCommCtrlServiceStub(object):
    """node -> tester
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportReady = channel.unary_unary(
                '/testerpb.TesterCommCtrlService/ReportReady',
                request_serializer=tester__pb2.NodeMeta.SerializeToString,
                response_deserializer=tester__pb2.CmdReply.FromString,
                _registered_method=True)


class TesterCommCtrlServiceServicer(object):
    """node -> tester
    """

    def ReportReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesterCommCtrlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportReady': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportReady,
                    request_deserializer=tester__pb2.NodeMeta.FromString,
                    response_serializer=tester__pb2.CmdReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testerpb.TesterCommCtrlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testerpb.TesterCommCtrlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TesterCommCtrlService(object):
    """node -> tester
    """

    @staticmethod
    def ReportReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testerpb.TesterCommCtrlService/ReportReady',
            tester__pb2.NodeMeta.SerializeToString,
            tester__pb2.CmdReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
